### PR TITLE
Test ABAP Lint

### PR DESCRIPTION
**Pull request by OberstVonGatow**

### CODE REVIEW

**Comment by larshp** [comment]
Hi, 👋 
By default, all rules are enabled in abaplint

you can add the `abaplint.json` configuration file to enable and disable rules, I recommend editing the file in vscode with the [abaplint extension](https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint) installed

rules are documented at https://rules.abaplint.org

let me know if I can help with anything

**Comment by larshp** [comment]
set rules to false to completely disable a rule, example:
`"abapdoc": false,`

**Comment by OberstVonGatow** [comment]
Hey Lars and thanks for your help.
I will change some to false but not all. I think i will leave some checks to "Info" to remind me that there are always things to improve 😊
What i don't understand are the message errors. (as seen in PullRequest "abaplint test2")
`Check failure on line 126 in src/zabap_generator.prog.abap
@abaplint abaplint / abaplint
Message number "009" not found in class "zmc_abap_generator"
https://rules.abaplint.org/message_exists
`
When i look into the message class the messages are there.

**Comment by larshp** [comment]
yea, I actually looked at https://github.com/OberstVonGatow/AbapGenerator/blob/main/src/zmc_abap_generator.msag.xml#L13 earlier today, something looks wrong with it, is English the primary language for the object? Line [20](https://github.com/OberstVonGatow/AbapGenerator/blob/main/src/zmc_abap_generator.msag.xml#L20) is just translations, the messages should be under line [13](https://github.com/OberstVonGatow/AbapGenerator/blob/main/src/zmc_abap_generator.msag.xml#L13)

**Comment by OberstVonGatow** [comment]
I could have done something wrong with the language settings. I will commit the messages again later.
Maybe it could also have something to do that i made everything in the 1909 Dev Docker Image.

**Comment by larshp** [comment]
not sure, but try taking a look at the language settings

as an example https://github.com/abapGit-tests/MSAG_simple/blob/main/src/zag_unit_test.msag.xml#L14 has the MSGNR under `<T100>` -> `<T100>`

**Comment by OberstVonGatow** [comment]
You were right there was something wrong with the messages. Now it works.

**Pull request closed without merging**
